services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: dhm
    ports:
      - 3306:3306
    volumes:
      - my-db-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: localhost
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  my-db-volume: