spring:
  cloud:
    gateway:
      routes:
        - id: account
          uri: http://localhost:8084
          predicates:
          - Path=/accounts
  application:
    name: gateway
server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/