spring:
  cloud:
    gateway:
      routes:
        - id: account
          uri: lb://account
          predicates:
          - Path=/accounts/**
        - id: card
          uri: lb://card
          predicates:
            - Path=/cards/**
        - id: transference
          uri: lb://transference
          predicates:
            - Path=/transference/**

  application:
    name: gateway

server:
  port: 8087
